name: Update OpenAPI Specification for shortcut.com

on:
  workflow_dispatch:
  schedule:
  # On Fridays
  - cron: '0 12 * * 5'

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.8.22

jobs:
  update_openapi_specification:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
      id: generate-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
      with:
        version: ${{ env.UV_VERSION }}
    - run: uv run --script scripts/update_openapi.py
    - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        title: 'chore: Update OpenAPI Specification for shortcut.com'
        token: ${{ steps.generate-token.outputs.token }}
