name: Update OpenAPI Specification for shortcut.com

on:
  workflow_dispatch:
  schedule:
  # On Fridays
  - cron: '0 12 * * 5'

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.9.9

jobs:
  update_openapi_specification:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
      id: generate-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        version: ${{ env.UV_VERSION }}
    - run: uv run --script scripts/update_openapi.py
    - uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
      with:
        title: 'chore: Update OpenAPI Specification for shortcut.com'
        token: ${{ steps.generate-token.outputs.token }}
        signoff: true
