name: Update OpenAPI Specification for shortcut.com

on:
  workflow_dispatch:
  schedule:
  # On Fridays
  - cron: '0 12 * * 5'

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.9.18

jobs:
  update_openapi_specification:
    name: Update Catalog
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Required by peter-evans/create-pull-request
      pull-requests: write  # Required by peter-evans/create-pull-request
    steps:
    - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      id: generate-token
      with:
        app-id: ${{ vars.RESERVOIR_GITHUB_APP_ID }}
        private-key: ${{ secrets.RESERVOIR_GITHUB_APP_PKEY }}
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        version: ${{ env.UV_VERSION }}
    - run: uv run --script scripts/update_openapi.py
    - run: uv run pytest --snapshot-update tests/test_schema_evolution.py
    - id: check_snapshot_changes
      continue-on-error: true
      run: git diff --quiet tests/__snapshots__
    - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
      if: steps.check_snapshot_changes.outcome == 'failure'
      with:
        title: 'chore: Update tap catalog from fresh OpenAPI Specification for shortcut.com'
        commit-message: 'chore: Update tap catalog from fresh OpenAPI Specification for shortcut.com'
        token: ${{ steps.generate-token.outputs.token }}
        signoff: true
